### PR TITLE
Update open-balena-base to v10.0.2

### PR DESCRIPTION
**Pull request by wrboyce**

### CODE REVIEW

**Review by Page- — COMMENTED** [review]
This should be a major

**Review by thgreasi — APPROVED** [review]

**Comment by thgreasi** [comment]
Oh my @wrboyce , I didn't see @Page- 's comment :disappointed: sorry.
Can you open a separate PR?

**Comment by wrboyce** [comment]
@thgreasi its all good, I had re-pushed with a major change type :)

**Comment by thgreasi** [comment]
Pheew :relieved:

**Pull request merged**
