### PR TITLE
Bump open-balena-base

### PR DESCRIPTION
**Pull request by ab77**
Dependency: https://github.com/balena-io-modules/open-balena-base/pull/141

* remove CircleCI builds (ci/circleci checks can be ignored; ResinCI/* must pass once dependency is merged)

Update open-balena-base to 11.3.8
Update open-balena-base from 11.3.5 to 11.3.8

Change-type: patch

### CODE REVIEW

**Comment by thgreasi** [comment]
@balena-ci retest

**Comment by thgreasi** [comment]
Oh I see why it fails...
LGTM :+1: @ab77 once open-balena-base in merged.
Even though I'm thinking it might make sense to merge this repo with open-balena-base at some later point (which I keep saying...).

**Comment by ab77** [comment]
>  it might make sense to merge this repo with open-balena-base at some later point (which I keep saying...).

Yes please :)

If we can find [that guy](https://github.com/balena-io/balena-ui/commit/94cc79ed92f614bac149ca57e7bcaf9b5da9fdba#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557) who split them up in the first place...

**Comment by ab77** [comment]
@balena-ci I self-certify!

**Pull request merged**
