### PR TITLE
Delete .github directory

### PR DESCRIPTION
**Pull request by dfunckt**
Change-type: patch

### CODE REVIEW

**Comment by dfunckt** [comment]
@balena-ci I self-certify!

**Comment by thgreasi** [comment]
Already did that on #71, but I guess balenaCI has enough load atm...

**Comment by dfunckt** [comment]
@thgreasi I blindly opened PRs, feel free to just close them if you find more duplicates from me.

**Comment by thgreasi** [comment]
Also did that myself @dfunckt :sweat_smile: (opening blindly)
It's like during the docs release party! PR mania!

**Pull request closed without merging**
